#!/usr/bin/env bash
# Transfers a file from Holberton's client to another.
# Accepts four arguments:
#+    The path to the file to be transferred.
#+    The IP of the server to transfer the file to.
#+    The username that scp connects with.
#+    The path to the SSH private key that scp uses.

if [ "$#" -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

file_path=$1
ip=$2
username=$3
key_path=$4

scp -o StrictHostKeyChecking=no -i $key_path $file_path $username@$ip:~/
