#!/usr/bin/env bash
# Configure HAProxy load balancer server

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy=2.6.\*
echo "frontend http
        bind *:80
        mode http
        default_backend web-backend
    backend web-backend
        balance roundrobin
        server 101426-web-01 100.25.158.177
        server 101426-web-02 54.157.170.783" >> /etc/haproxy/haproxy.cfg

service haproxy restart
