#!/usr/bin/env bash
# A bash script that changes nginx port to 80
sudo apt-get update
sudo service nginx stop
sudo sed -i 's/listen 8080 default_server;/listen 80 default_server;/' /etc/nginx/sites-enabled/default
sudo service nginx start

