#!/usr/bin/env bash
# A bash script that changes nginx port to 80
sudo awk '{sub("listen 8080 default_server;", "listen 80 default_server;")}1' /etc/nginx/sites-enabled/default > temp && sudo mv temp /etc/nginx/sites-enabled/default
# restart Nginx
sudo service nginx restart

