#!/usr/bin/env bash
#Debugging Script
# Remove the default Nginx configuration file for port 8080
rm /etc/nginx/sites-enabled/default

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

service nginx restart
