#!/usr/bin/env bash
# make it  short and sweet.
sudo sed -i 's/listen 8080 default_server/listen 80 default_server/' /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo service nginx stop
