#!/usr/bin/env bash
# Configures a ufw firewall to block all incoming traffic

apt-get install ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
ufw disable
ufw enable

#Exceptions
ufw default deny incoming
ufw default allow outgoing
utf allow 80/tcp
utf allow OpenSSH
ufw allow 22/tcp
ufw allow 443/tcp
